name: Pytest
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - master

jobs: 
  test:
    name: "py${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8 , 3.9, "3.10"]
    steps:
      - name: Setup python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v2.4.0
      - name: test-basics
        if: matrix.python-version == '3.8'
        run: python setup.py test
      - name: test with dependencies install py3.X
        if: matrix.python-version != '2.7'
        run: |
             pip install matplotlib scipy dask numpy pandas
             python setup.py test
      - name: test with dependencies install py2.7
        if: matrix.python-version == '2.7'
        run: |
          pip install scipy dask numpy pandas
          python setup.py test
      - name: goodbye
        run: echo goodbye
